# Generated by Django 5.2.7 on 2025-11-17 22:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_program_id_alter_programtype_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("main_title_part1", models.CharField(blank=True, max_length=50)),
                ("main_title_part2", models.CharField(blank=True, max_length=50)),
                ("main_title_part3", models.CharField(blank=True, max_length=50)),
                ("main_title", models.CharField(blank=True, max_length=255)),
                ("main_subtitle", models.CharField(blank=True, max_length=500)),
                ("main_image", models.CharField(blank=True, max_length=500)),
                ("body", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
