# Generated by Django 5.2.7 on 2025-11-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_logo_navbar_alter_homepage_page_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="navbar",
            name="url",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
