# Generated by Django 5.2.7 on 2025-11-18 01:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_navbar_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionSidebarItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
