# Generated by Django 5.2.7 on 2025-11-18 17:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_admissionsidebaritem"),
    ]

    operations = [
        migrations.CreateModel(
            name="UndergraduateAddmissionReqPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_title", models.CharField(default="Admissions", max_length=100)),
                ("page_heading", models.CharField(max_length=255)),
                ("admission_requirement_heading", models.CharField(max_length=255)),
                ("admission_requirement_description", models.TextField()),
                ("english_requirements_description", models.TextField()),
                (
                    "language_req_description",
                    models.TextField(
                        blank=True,
                        help_text="Optional text after the bullet list",
                        null=True,
                    ),
                ),
                ("application_deadlines", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_image",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_subtitle",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="navbar",
            name="menu_item",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="navbar",
            name="url",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="LanguageReqExemptionBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exemption_bullets",
                        to="pages.undergraduateaddmissionreqpage",
                    ),
                ),
            ],
        ),
    ]
