# Generated by Django 5.2.7 on 2025-11-18 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_rename_language_req_description_undergraduateaddmissionreqpage_language_req_exemtion_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateAdmissionPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_title', models.CharField(default='Graduate', max_length=100)),
                ('page_heading', models.CharField(max_length=255)),
                ('admission_req_heading', models.CharField(max_length=255)),
                ('admission_req_desc', models.TextField()),
                ('find_supervisor_heading', models.CharField(max_length=255)),
                ('find_supervisor_descr', models.TextField()),
                ('application_deadline_heading', models.CharField(max_length=255)),
                ('application_deadline_description', models.TextField()),
                ('fast_track_heading', models.CharField(max_length=255)),
                ('fast_track_description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='undergraduateaddmissionreqpage',
            name='page_title',
            field=models.CharField(default='Undergraduate', max_length=100),
        ),
        migrations.CreateModel(
            name='AdmissionReqBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_bullets', to='pages.graduateadmissionpage')),
            ],
        ),
    ]
