# Generated by Django 5.2.7 on 2025-11-18 19:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0013_graduateadmissionpage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlineCoursesPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "page_title",
                    models.CharField(default="Online Courses", max_length=100),
                ),
                ("page_heading", models.CharField(max_length=255)),
                ("highschool_heading", models.CharField(max_length=255)),
                ("highschool_description", models.TextField()),
                ("undergrad_heading", models.CharField(max_length=255)),
                ("undergrad_description", models.TextField()),
                ("grad_heading", models.CharField(max_length=255)),
                ("grad_description", models.TextField()),
                ("other_req_heading", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="OnlineCoursesBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_bullets",
                        to="pages.onlinecoursespage",
                    ),
                ),
            ],
        ),
    ]
