# Generated by Django 5.2.7 on 2025-11-18 20:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0014_onlinecoursespage_onlinecoursesbullet"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "page_title",
                    models.CharField(default="Funding & Scholarships", max_length=100),
                ),
                ("financial_heading", models.CharField(max_length=255)),
                ("financial_description", models.TextField()),
                ("entrance_scholarship_heading", models.CharField(max_length=255)),
                ("entrance_scholarship_description", models.TextField()),
                ("in_program_scholarship_heading", models.CharField(max_length=255)),
                ("in_program_scholarship_description", models.TextField()),
            ],
        ),
    ]
