# Generated by Django 5.2.7 on 2025-11-18 21:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0015_fundingpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_title", models.CharField(default="Contact Us", max_length=100)),
                (
                    "office_name",
                    models.CharField(default="Admission Office", max_length=255),
                ),
                ("office_room", models.CharField(default="Room 3118", max_length=100)),
                (
                    "office_location",
                    models.CharField(
                        default="NextGen University, St. John's, Canada", max_length=255
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("fax", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
