# Generated by Django 5.2.7 on 2025-11-18 23:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0017_faculty_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="url",
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.CreateModel(
            name="DepartmentPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_title", models.CharField(max_length=255)),
                ("main_heading", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("achievements", models.TextField(blank=True)),
                ("advisor_name", models.CharField(blank=True, max_length=255)),
                ("advisor_title", models.CharField(blank=True, max_length=255)),
                ("advisor_email", models.EmailField(blank=True, max_length=254)),
                ("advisor_office", models.CharField(blank=True, max_length=255)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="pages.department",
                    ),
                ),
            ],
        ),
    ]
