# Generated by Django 5.2.8 on 2025-11-28 22:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0018_alter_department_url_departmentpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admissionreqbullet",
            name="page",
        ),
        migrations.DeleteModel(
            name="AdmissionSidebarItem",
        ),
        migrations.DeleteModel(
            name="ContactPage",
        ),
        migrations.RemoveField(
            model_name="department",
            name="faculty",
        ),
        migrations.RemoveField(
            model_name="departmentpage",
            name="department",
        ),
        migrations.DeleteModel(
            name="FundingPage",
        ),
        migrations.DeleteModel(
            name="HomePage",
        ),
        migrations.RemoveField(
            model_name="languagereqexemptionbullet",
            name="page",
        ),
        migrations.DeleteModel(
            name="Logo",
        ),
        migrations.DeleteModel(
            name="Navbar",
        ),
        migrations.RemoveField(
            model_name="onlinecoursesbullet",
            name="page",
        ),
        migrations.DeleteModel(
            name="AdmissionReqBullet",
        ),
        migrations.DeleteModel(
            name="GraduateAdmissionPage",
        ),
        migrations.DeleteModel(
            name="Faculty",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="DepartmentPage",
        ),
        migrations.DeleteModel(
            name="LanguageReqExemptionBullet",
        ),
        migrations.DeleteModel(
            name="UndergraduateAddmissionReqPage",
        ),
        migrations.DeleteModel(
            name="OnlineCoursesBullet",
        ),
        migrations.DeleteModel(
            name="OnlineCoursesPage",
        ),
    ]
