# Generated by Django 5.2.7 on 2025-11-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anonymousfeedback",
            name="type",
            field=models.CharField(
                choices=[("Bug", "bug"), ("Issue", "issue")],
                max_length=255,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="type",
            field=models.CharField(
                choices=[("Bug", "bug"), ("Issue", "issue")],
                max_length=255,
                verbose_name="Type",
            ),
        ),
    ]
